from .router_prompts import (
    UNIFIED_ROUTER_PROMPT,
)
from .graph_rag_prompts import (
    SCHEMA_DESCRIPTION,
    CYPHER_GENERATION_PROMPT,
    QUERY_REFINEMENT_PROMPT,
)
from .spotify_prompts import (
    TOOL_DESCRIPTIONS,
    TOOL_SELECTION_PROMPT,
    MULTI_TOOL_PLANNING_PROMPT,
)
from .synthesis_prompts import (
    RESPONSE_SYNTHESIS_PROMPT,
    MULTI_RESULT_SYNTHESIS_PROMPT,
    CHAINED_RESULT_SYNTHESIS_PROMPT,
    ERROR_SYNTHESIS_PROMPT,
)

__all__ = [
    "UNIFIED_ROUTER_PROMPT",
    "SCHEMA_DESCRIPTION",
    "CYPHER_GENERATION_PROMPT",
    "QUERY_REFINEMENT_PROMPT",
    "TOOL_DESCRIPTIONS",
    "TOOL_SELECTION_PROMPT",
    "MULTI_TOOL_PLANNING_PROMPT",
    "RESPONSE_SYNTHESIS_PROMPT",
    "MULTI_RESULT_SYNTHESIS_PROMPT",
    "CHAINED_RESULT_SYNTHESIS_PROMPT",
    "ERROR_SYNTHESIS_PROMPT",
]
